Name = input('What is your Name ?: ')
HourlyRate = float(input('What is your hourly rate ?: '))
HoursWorked = float(input('How many hours did you work this week ?: '))
GrossWages = round(HourlyRate * HoursWorked, 10)
NetWages = round(HourlyRate * HoursWorked * 0.80, 3)
print('Name: ',Name)
print('Gross Wages = €',GrossWages)
print ('Net Wages = €',NetWages,)
Sallary = round(NetWages*52)
GrossSal = round(GrossWages*52)
print('Gross Sallary € ',GrossSal)
print('Net Sallary € ',Sallary)