print("What is your age? ")
print(21)
print("My age is 21")
print("My age is", 21)
print("I am", 18, "and my friend is", 21)
print("The print command", "can handle", "more than 1 string.")
print("")
print(21)
print("21")